spring:
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ewm-stats
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  cloud:
    config:
      enabled: false
      discovery:
        enabled: false
  config:
    import: "optional:configserver:"

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
